version: '3'
services:
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: production
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql_data:/var/lib/postgresql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d myapp_development -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    container_name: rails_app
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/myapp/node_modules
    environment:
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4444:4444
  redis:
    image: "redis:7.0-alpine"
    volumes:
      - redis_volume:/data
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
  # sidekiq:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.sidekiq
  #   command: bundle exec sidekiq
  #   volumes:
  #     - .:/myapp
  #   depends_on:
  #     - db
  #     - redis


volumes:
  redis_volume:
  bundle_data:
  postgresql_data:
  node_modules: