// Entry point for the build script in your package.json
import "@hotwired/turbo-rails"
import "./controllers"
import * as bootstrap from "bootstrap"
import "./move_chat.js"
import "./board_thumbnail.js"
import "./board_frame.js"
import "./error_message.js"
import "./login.js"
import "./mypage.js"
import "./users.js"
